### PR TITLE
Fix issues with whitespace

### LINKED ISSUE #1: Lack of line feed characters results in garbled text on wider screens
When viewed on screens wider than ~850px, the bot's comments are distorted and unreadable. This is evident on both old and new Reddit:

amogus

This can be easily fixed by adding line feed characters to the sprite definitions in `cocks.json`. Alternatively, some preprocessing may be introduced in `index.ts` to insert line feeds automatically.

Please remember that in order to force a line break in Reddit Markdown, you must insert two spaces at the end of the line. Some third party clients have been known to ignore mid-paragraph line breaks and only support the new paragraph syntax (double line feed). You may consider going with that instead for compatibility.

Not trying to take a jab at anyone, but it surprises me that this bug has gone unnoticed for almost two weeks. Have you been developing this bot on mobile?

### PR DESCRIPTION
**Pull request by Lachcim**
This pull request resolves the issues discussed in #1. Closes #1.

I was able to run the bot locally to verify that it is working correctly with the changes in place. You may view example bot replies here: https://reddit.com/r/css_irl_bot/comments/mtwsnr/aucb_test/

Because you didn't specify your stance on the line break vs new paragraph issue, I decided to go for the safe option and used double line feed to mark new lines. This has the side effect that the ASCII art is slightly vertically elongated. This may be easily changed in the future.

While working on the whitespace, I noticed that sprite 0 contained a series of U+200E LEFT-TO-RIGHT MARK Unicode characters. I believe they were placed there by mistake so I removed those.

### CODE REVIEW

**Comment by Lachcim** [comment]
I advise you to take a look at the new sprites on different clients before merging this request. The elongation may be significant on some platforms, including new Reddit.

**Comment by Lachcim** [comment]
Actually, I reversed my decision regarding line breaks on the basis that:

1. Line breaks look better on platforms that support them
2. The platforms that don't support them are mobile devices with narrow screens, and as such are not affected by the issue

You can see both variants on the Reddit page I linked.

**Comment by nlanson** [comment]
Thanks for the PR. 

I have checked the text on different platforms on 3 different devices.
Here are the results:

## Desktop
### New Client
- On the new Reddit browser client, it is slightly elongated but somewhat tolerable. Not the optimal cock but not bad.
desktop new
### Old Client
- On the old Reddit browser client it looks great. Not as elongated as the new client.
desktop old

### Overall desktop
The ASCII is slightly elongated but very much tolerable. As desktop screens tend to be larger, the space between each line was not as noticeable.\
OK

## Mobile
### iOS App
- On the iOS Reddit app, the elongation is the same as the new desktop client, however as the screen is smaller the elongation is much more noticeable. Not the optimal cock that I had envisioned when the bot was created.
- It seems that the text does better when the comment is nested further down in a comment.
ios App
### iOS Browser
- Very stretched out and frankly unrecognizable unless you really try hard.\
For comparison, the current configuration [looks like this](https://imgur.com/a/Dj0dbi5) on iOS browser
ios Browser

### Overall iOS
The ASCII elongation was much more noticeable on the official mobile app and on browser it was unrecognizable.\
NOT OK

## So What Can Be Done Instead?
I have though about an argument system where commenters can specify whether they want it formatted for desktop or mobile.

For example: when a user comments `u/AmongUsCockBot -D` the bot will respond with the desktop friendly format and when a user comments `u/AmongUsCockBot -M` the bot will respond with the mobile friendly format. 

This however would reduce the simplicity of the bot. I wrote this bot with the intention of quick, effortless among us cock delivery. Adding arguments in my opinion makes the bot over complicated and would just become a feature that ends up getting unused. It could possible be an optional feature where if no arguments are passed one of the formats are returned.

Also with issue of deploying significant changes to the bot, there would need to be significant community approval for changes to be put in place. The bot currently has around 1800 reddit followers and a mention every few minutes. Changing the format to favor one client over another without consensus is not favorable but that's an issue for another time.

**Comment by Lachcim** [comment]
Thanks for your analysis. I'd like to draw your attention to a last-minute change that I made in a1b31bd which changes the way line breaks are implemented. I implemented this change because I had indeed encountered the problems you mentioned. You may want to take a look at the three new comments left by the bot in the thread.

**Comment by nlanson** [comment]
I see the three new comments, however as they are not replies to a top level comment and they are down further in the chain of commenting, it is hard to know if it is an accurate representation and it maybe showing up differently.

I did try and summon your bot to test your changes however it did not show up. If you could leave a new top level comment summoning the bot it would be great. 

Thanks

**Comment by Lachcim** [comment]
Top-level replies available here:

https://reddit.com/r/css_irl_bot/comments/mtwsnr/aucb_test/gv2kgg7/
https://reddit.com/r/css_irl_bot/comments/mtwsnr/aucb_test/gv2kg5j/
https://reddit.com/r/css_irl_bot/comments/mtwsnr/aucb_test/gv2kfes/

**Comment by nlanson** [comment]
It looks great.

I will merge into a new test branch, run a few tests on my side and implement if all goes well.
Thanks a lot.

## Results

### iOS App
image
image
image

### Desktop (New)
image
image
image

**Review by nlanson — COMMENTED** [review]
New changes work much better.

**Comment by Lachcim** [comment]
> Actually, I reversed my decision regarding line breaks on the basis that:
> 
> 1. Line breaks look better on platforms that support them
> 2. The platforms that don't support them are mobile devices with narrow screens, and as such are not affected by the issue

For future readers, this false assumption is what led to issue #4.

I find it a constant source of astonishment that the official Reddit app: (i) disregards well-established Reddit Markdown syntax, and (ii) it does so by removing the whitespace altogether. Somebody ought to compile a list of all the idiosyncrasies of Reddit clients so that no one else has to learn from their (expensive) mistakes.

**Pull request merged**
